import { ArrowRight, CheckCircle2, Leaf, ShieldCheck, Sun, Zap } from "lucide-react";
import { Link } from "react-router-dom";

const Landing = () => (
  <div className="min-h-screen bg-[#f6f8f6] text-slate-900">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
      <Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-lg font-bold text-white shadow-lg shadow-green-200">S</span><span><span className="block font-heading text-lg font-semibold tracking-tight">SolarShare</span><span className="block text-[10px] font-semibold uppercase tracking-[0.15em] text-slate-400">Energy exchange</span></span></Link>
      <div className="flex items-center gap-3"><Link to="/login" className="hidden text-sm font-semibold text-slate-600 hover:text-slate-900 sm:block">Log in</Link><Link to="/register" className="btn-primary px-4 py-2">Get started <ArrowRight size={16} /></Link></div>
    </header>

    <main className="mx-auto max-w-7xl px-5 pb-14 pt-8 sm:px-8 lg:px-10 lg:pb-20 lg:pt-14">
      <section className="grid items-center gap-12 lg:grid-cols-[1.04fr_0.96fr] lg:gap-16">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-green-100 bg-green-50 px-3 py-1.5 text-xs font-semibold text-green-800"><span className="h-1.5 w-1.5 rounded-full bg-green-500" /> Community-powered clean energy</div><h1 className="mt-6 max-w-2xl font-heading text-4xl font-semibold leading-[1.08] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Your sunshine can power the neighbourhood.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">SolarShare helps households sell surplus solar power, while nearby consumers buy clean energy directly from their community.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="btn-primary px-5 py-3">Join SolarShare <ArrowRight size={17} /></Link><Link to="/login" className="btn-secondary px-5 py-3">I already have an account</Link></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm text-slate-600"><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-primary" /> Local energy trading</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-primary" /> Simple wallet settlement</span></div></div>

        <div className="relative mx-auto w-full max-w-xl"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_18px_50px_rgba(15,23,42,0.10)] sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">SolarShare network</p><h2 className="mt-1 font-heading text-xl font-semibold">Energy, shared locally</h2></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-50 text-amber-500"><Sun size={23} /></span></div><div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-2xl bg-slate-900 p-4 text-white"><p className="text-xs text-slate-300">Solar home</p><p className="mt-2 text-sm font-semibold">Surplus energy</p><div className="mt-4 flex items-end gap-1"><span className="h-4 w-2 rounded-t bg-green-300" /><span className="h-7 w-2 rounded-t bg-green-300" /><span className="h-10 w-2 rounded-t bg-green-300" /><span className="h-6 w-2 rounded-t bg-green-300" /><span className="h-12 w-2 rounded-t bg-green-300" /></div></div><div className="grid h-10 w-10 place-items-center rounded-full border border-green-200 bg-green-50 text-primary"><ArrowRight size={19} /></div><div className="rounded-2xl bg-green-50 p-4 text-green-950"><p className="text-xs text-green-700">Nearby home</p><p className="mt-2 text-sm font-semibold">Clean energy</p><div className="mt-4 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white text-primary"><Zap size={14} /></span><span className="text-xs font-semibold text-green-800">Direct purchase</span></div></div></div><div className="mt-6 rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-800">Transparent by design</p><span className="text-xs font-semibold text-primary">Live settlement</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full w-[72%] rounded-full bg-primary" /></div><p className="mt-2 text-xs text-slate-500">Measure, list, purchase, and settle — all in one place.</p></div></div></div>
      </section>

      <section className="mt-16 grid gap-4 md:grid-cols-3 lg:mt-24"><div className="panel p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><Sun size={19} /></span><h3 className="mt-5 font-heading text-lg font-semibold">Put surplus to work</h3><p className="mt-2 text-sm leading-6 text-slate-600">List unused solar generation and set the price that makes sense for you.</p></div><div className="panel p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-green-50 text-green-700"><Leaf size={19} /></span><h3 className="mt-5 font-heading text-lg font-semibold">Buy local, clean energy</h3><p className="mt-2 text-sm leading-6 text-slate-600">Compare nearby offers and choose cleaner energy from your own community.</p></div><div className="panel p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><ShieldCheck size={19} /></span><h3 className="mt-5 font-heading text-lg font-semibold">Settle with confidence</h3><p className="mt-2 text-sm leading-6 text-slate-600">Every transaction is tracked, with wallet activity and energy history in one dashboard.</p></div></section>
    </main>
  </div>
);

export default Landing;
